### ISSUE TITLE
G-Sync/VRR does not appear to work

### ISSUE THREAD

**Issue by beefcat666** [sultim-t/xash-rt#10]
Game presents uneven frame pacing on Windows unless your framerate is an integer factor of your refresh rate. The in-game vsync setting has little impact on this behavior apart from capping the frame rate to the refresh rate.

Expected behavior: Frames should be delivered to the GPU when they are ready rather than trying to synchronize with the refresh rate.

I used the nvidia control panel to cap the framerate to 90 FPS (since my GPU can maintain that framerate consistently at my desired settings/resolution). Strafing while looking at a wall looks choppy and not smooth despite running at a locked 90 frames per second.

I expect similar behavior with FreeSync on Radeon and Arc GPUs, but I do not have samples of either of these to test with.

**Comment by a1batross** [comment]
Read my comment from here: https://github.com/sultim-t/xash-rt/issues/25#issuecomment-1442661030

**Comment by green-s** [comment]
Even with those commands/newer build, G-Sync doesn't seem to be working according to the Nvidia indicator. The game looks choppy and input feels pretty laggy compared to other games at the same framerate (>70 for me).

**Edit:**

Just tried #35 and it's not working with that build either.

**Comment by beefcat666** [comment]
This issue appears resolved as of 1.0.5a, at least on my system (Windows 11, RTX 3080)
