### ISSUE TITLE
Artifacting around GUI/ lower half of screen

### ISSUE THREAD

**Issue by Lizziezilla** [sultim-t/xash-rt#111]
Got a issue with weird noise artifacting around GUI elements and in lower half of the screen.  

Now was perfectly fine with the RX 6800 xt newest driver but after upgrading the GPU to a RX 7900 xtx newest driver this issue appeared. 

Does not occur on other RT games, Quake II RT, Cyberpunk or Shadow of the Tombraider. 

![image](https://user-images.githubusercontent.com/126737100/222310049-8e3d9685-bb62-44ea-97be-ab00c7761ead.png) 

![image](https://user-images.githubusercontent.com/126737100/222310586-3485a406-e74c-4e64-b8fa-1cb40eba3c70.png)

![image](https://user-images.githubusercontent.com/126737100/222310647-f34381f8-d832-4edc-9933-d23f33a36c93.png)

![image](https://user-images.githubusercontent.com/126737100/222310755-79e6c941-78da-4927-9415-7726f547b265.png)

**Comment by sultim-t** [comment]
Should be fixed in [1.0.5](https://github.com/sultim-t/xash-rt/releases/tag/1.0.5a)

--
Duplicate of #3
