### ISSUE TITLE
c2a5w incorrect walls with rtx renderer

### ISSUE THREAD

**Issue by phant** [sultim-t/xash-rt#117]
With RTX renderer walls are different

Map c2a5w 
Position
![c2a5w xash3d_2023_03_03_23_52_34_862_cr](https://user-images.githubusercontent.com/805222/222816666-6a957b15-ae9f-46e2-ac15-565155283b92.png)
<details>
  <summary>Screenshots near wall</summary>
old

![1 nor](https://user-images.githubusercontent.com/805222/222819596-3f5187cd-ae0e-4464-bcb8-fecdffd2fa8f.jpg)
rt
![2 rt](https://user-images.githubusercontent.com/805222/222819586-77569b3a-54ff-4fdf-b96f-64d568627c2d.jpg)

</details>

<details>
  <summary>Screenshots overview</summary>

old
![3 nor](https://user-images.githubusercontent.com/805222/222820407-f69b412e-2bc6-4fca-82ea-162001c3fb89.jpg)
rt
![4 rt](https://user-images.githubusercontent.com/805222/222820396-5fcf5285-df9a-464a-b695-3506365d666d.jpg)

</details>

**Comment by sultim-t** [comment]
Yup, it's done to prevent some of the god rays leaks...
