### ISSUE TITLE
Lighting not working correctly

### ISSUE THREAD

**Issue by jjjdotcom** [sultim-t/xash-rt#118]
Lighting isn't working correctly. Any ideas on how to fix?
![Screenshot (16)](https://user-images.githubusercontent.com/81313396/222874932-dbd51e93-29bc-4d72-a870-8677ef71d1f5.png)
![Screenshot (17)](https://user-images.githubusercontent.com/81313396/222874936-1931754c-1333-4e40-82a0-39de142dd09c.png)
![Screenshot (18)](https://user-images.githubusercontent.com/81313396/222874937-d08edcc3-808b-45a0-893a-fb472065da7d.png)
![Screenshot (19)](https://user-images.githubusercontent.com/81313396/222874941-0e5e1cbd-84c3-4769-b150-3e3ce9d4f3bf.png)
![Screenshot (20)](https://user-images.githubusercontent.com/81313396/222874943-78ec5e31-0aa3-4b0d-b997-14a4a617b8a3.png)

**Comment by sultim-t** [comment]
This happens when `hl1-rt-resouces.zip` is not unzipped.

In [1.0.5a](https://github.com/sultim-t/xash-rt/releases/tag/1.0.5a) installation process was simplified
