### ISSUE TITLE
its dark

### ISSUE THREAD

**Issue by TheMonkeandratgod** [sultim-t/xash-rt#120]
at first i thought this was intended, but certain areas with lights have no light at all.
![darkhallways](https://user-images.githubusercontent.com/107513207/222905967-ad7982b6-00b3-45b0-aa01-04ec432f65cd.png)

**Comment by sultim-t** [comment]
Is this [1.0.5a](https://github.com/sultim-t/xash-rt/releases/tag/1.0.5a) or [1.0.5](https://github.com/sultim-t/xash-rt/releases/tag/1.0.5)?

**Comment by TheMonkeandratgod** [comment]
> Is this [1.0.5a](https://github.com/sultim-t/xash-rt/releases/tag/1.0.5a) or [1.0.5](https://github.com/sultim-t/xash-rt/releases/tag/1.0.5)?

1.0.5

**Comment by TheMonkeandratgod** [comment]
aight, i switched and its much better now. thank you!
