### ISSUE TITLE
Host init error: cant find physical device with raytracing sypport

### ISSUE THREAD

**Issue by ghost** [sultim-t/xash-rt#122]
havent been able to open it once at all and it keeps displaying this message ive tried everything

**Comment by fm3at** [comment]
> 
what video card do you have?

**Comment by ghost** [comment]
nvidia 1650 with max q design @fm3at

**Comment by TigerTank2** [comment]
@fm3at

**Comment by fm3at** [comment]
> nvidia 1650 with max q design

this gpu dont have dedicated raytracing hardware, required for this mod
