### ISSUE TITLE
how to open command console

### ISSUE THREAD

**Issue by PAIDMAN** [sultim-t/xash-rt#131]
### Discussed in https://github.com/sultim-t/xash-rt/discussions/130

<div type='discussions-op-text'>

<sup>Originally posted by **gobasfourte** March  7, 2023</sup>
i got this bug 
https://www.reddit.com/r/HalfLife/comments/ianxeq/apprehension_ending_cut_scene_glitch/

and I need the console to resolve it . I try to do it in the original games but the save in the ray traced version cant be load .</div>

**Comment by chaosophy** [comment]
You can use the ' -console' switch to launch the game with the console enabled.
There is also a bat file...
\Program Files (x86)\Steam\steamapps\common\Half-Life\rt_bin\xash3d-console.bat

**Comment by PAIDMAN** [comment]
thank you
