### ISSUE TITLE
Won't launch - "W_LoadWadFile: could load gfx.wad"

### ISSUE THREAD

**Issue by eskild133** [sultim-t/xash-rt#166]
I unzipped it into Half Life, and tried opening xash3d.exe, but it just does this:
![image](https://user-images.githubusercontent.com/128265102/226145836-00582c11-9594-4be5-bbfc-283b140fa624.png)
Dunno what to do

**Comment by mastan-rus** [comment]
See 
https://github.com/sultim-t/xash-rt/issues/30#issuecomment-1442637561
https://github.com/sultim-t/xash-rt/issues/81#issuecomment-1447254872

**Comment by eskild133** [comment]
ohhh i'm dumb

thx
