### ISSUE TITLE
Xash Error Launching

### ISSUE THREAD

**Issue by ForgottenFauna** [sultim-t/xash-rt#17]
I've tried running xash.exe on a fresh install  (_I followed the method for a clean install that sultim said in #2 _ )and it displays this error message.
![image](https://user-images.githubusercontent.com/126155378/220870918-ff320dd3-e3e1-4150-867e-6e4c7dc1199e.png)

I've got a RX 6600 XT gpu aswell.

**Comment by a1batross** [comment]
You're supposed to unpack the ZIP archive contents to Half-Life folder, not `valve` folder or anywhere else, not move files. Just as is

I don't know why sultim choose this exact way of installing tbh but ok

**Comment by ForgottenFauna** [comment]
That worked, thank you.
