### ISSUE TITLE
Black screen when launching

### ISSUE THREAD

**Issue by junglejuz** [sultim-t/xash-rt#188]
4070ti with latest driver 531.68
Game doesn't launch with xash3d.exe. Just get a black screen with Not Responding down in the Windows task bar.

**Comment by lastleek** [comment]
How did you fix this?????

**Comment by RiceWitch** [comment]
you can't just leave everyone in the dark when you fix it bruh

**Comment by junglejuz** [comment]
apologies. I don't even remember what this was. I may have just given up on it.
