### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by System10RuKoGa** [sultim-t/xash-rt#19]
I decided to play it, and I think I did everything right... And it runs for a second and then crashes with this error
![image](https://user-images.githubusercontent.com/116139798/220928469-ee34f6f5-22a8-46a7-a93f-d17576b5467b.png)

**Comment by wenceslaorl** [comment]
> I decided to play it, and I think I did everything right... And it runs for a second and then crashes with this error ![image](https://user-images.githubusercontent.com/116139798/220928469-ee34f6f5-22a8-46a7-a93f-d17576b5467b.png)

Did you use dlss 3.1.1?

**Comment by Guidealorean** [comment]
> I decided to play it, and I think I did everything right... And it runs for a second and then crashes with this error ![image](https://user-images.githubusercontent.com/116139798/220928469-ee34f6f5-22a8-46a7-a93f-d17576b5467b.png)

What graphics card are you using? i have a AMD Radeon RX 500 and it doesn't have ray tracing support. Maybe your graphics card doesn't support it either?

**Comment by System10RuKoGa** [comment]
> > I decided to play it, and I think I did everything right... And it runs for a second and then crashes with this error ![image](https://user-images.githubusercontent.com/116139798/220928469-ee34f6f5-22a8-46a7-a93f-d17576b5467b.png)
> 
> What graphics card are you using? i have a AMD Radeon RX 500 and it doesn't have ray tracing support. Maybe your graphics card doesn't support it either?

I have an AMD A6-7310

**Comment by wenceslaorl** [comment]
> > > I decided to play it, and I think I did everything right... And it runs for a second and then crashes with this error ![image](https://user-images.githubusercontent.com/116139798/220928469-ee34f6f5-22a8-46a7-a93f-d17576b5467b.png)
> > 
> > 
> > What graphics card are you using? i have a AMD Radeon RX 500 and it doesn't have ray tracing support. Maybe your graphics card doesn't support it either?
> 
> I have an AMD A6-7310

Your gpu does not support Ray Tracing : (
