### ISSUE TITLE
No Dead Zones for Controllers

### ISSUE THREAD

**Issue by aallusti** [sultim-t/xash-rt#193]
Having issue where my movements with both sticks on XBOX One wireless controller have momentum. Once you stop moving a stick in a direction the camera continues slowly moving towards its original direction, almost like there are no dead zones and the game is still taking controller input.

Have recreated issue on two separate  XBOX One wireless controllers

**Comment by 0x4E69676874466F78** [comment]
You need to configure the "joystick" settings, for example via console commands, type joy_ and press `TAB` key, there's a deadzone.

**Comment by aallusti** [comment]
Are you referring to the console commands in HL1 base game? I cannot open console via "~" in RT mod, only in base game. Is there a separate key binding I'm not finding for console in HL1 + RT?

**Comment by 0x4E69676874466F78** [comment]
@aallusti Console works if you put -console to the game shortcut after exe (`...\rt_bin\xash3d.exe -console`). Keep in mind the console does NOT work in the menu, only in the game!

**Comment by aallusti** [comment]
Thank you very much for the detailed explanation. I have fixed my configuration
