### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Zorklis** [sultim-t/xash-rt#2]
![image](https://user-images.githubusercontent.com/85455465/220760935-d9a090d3-dfe8-4a68-bbfc-749d8ef0b500.png)

**Comment by ComradeTiki** [comment]
Same type of issue more-or-less: 
![image](https://user-images.githubusercontent.com/126134886/220818764-23e7c089-8d83-4390-889e-374e9f4ef079.png)

**Comment by sultim-t** [comment]
Maybe to try on a clean HL1 Steam build, by completely deleting `steamapps/common/Half-Life` folder and reinstalling the game from Steam? After downloading HL1, also remove all .cfg files from `Half-Life/valve` folder, as Steam synchronizes all of them.
And only after that install HL1RT on top

**Comment by 7Works** [comment]
> Maybe to try on a clean HL1 Steam build, by completely deleting `steamapps/common/Half-Life` folder and reinstalling the game from Steam? After downloading HL1, also remove all .cfg files from `Half-Life/valve` folder, as Steam synchronizes all of them. And only after that install HL1RT on top

Tried that, got same error:
![image](https://user-images.githubusercontent.com/126140383/220850249-b8209639-418b-4dcd-8ea5-5ae512b337e0.png)
![image](https://user-images.githubusercontent.com/126140383/220850262-91b2a9d7-feb8-4edd-8135-429ea24e3212.png)
The only difference here is that previously this errors showed up while black window of xash launcher was still opened, and now it closes immediately as these errors pop up.
Is there any way sending to you logs or something like that?

**Comment by zeberdee** [comment]
I've don everything that the installation instructions have said, and i end up just looking at a console and thats it? Once I exit the xash console, do i run the HL as normal? or do i use some other exe file?
Ok, now i've ran the HL and i still cant get the raytracing to work, use the 'x' key to turn on and off, and this is all i get in the console.

No detail texture mapping file: maps/c0a0_detail.txt
Unknown command: VModEnable
Unknown command: rt_classic_toggle
Unknown command: rt_classic_toggle

**Comment by DankmemeBunny** [comment]
I did a complete reinstall and still ended up with this exact error, perphaps it something to do with the GPU? I have a 1060 which according to GPU-Z it does support ray tracing.

**Comment by superblobster** [comment]
> Maybe to try on a clean HL1 Steam build, by completely deleting `steamapps/common/Half-Life` folder and reinstalling the game from Steam? After downloading HL1, also remove all .cfg files from `Half-Life/valve` folder, as Steam synchronizes all of them. And only after that install HL1RT on top

Did all that. Doesn't work. Please fix the mod.

**Comment by ComradeTiki** [comment]
> perphaps it something to do with the GPU? I have a 1060 

 I'm on a 1080

**Comment by lexa2** [comment]
Well I'm hitting the xash error complaining about "can't initialize cl_dlls/client_amd64.dll" too. Thing is I don't have client_amd64.dll anywhere under my HL1 installation folder. This is a Steam version, local files check passes OK, all updates seem to be installed.

What I don't get is how is it supposed to work if HL1 binaries in Steam version are 32bit while xash build with RT patches is a 64bit. Am I missing something? Might it be that there are several different HL1 builds/apps available on Steam some being 32bit only and another having client_amd64.dll available alongside 32bit client.dll?

**Comment by lexa2** [comment]
Nevermind, found *_amd64.dll files under rt directory. Looks like more thorought investigations is required for my case, will post update on any progress.

**Comment by lexa2** [comment]
Got it running. Trick was to run xash3d.exe executable from windows file explorer window instead of running it from Far Manager. Have no idea at the moment what's the deal with it and what are exact run environment differences when running by double-clicking in explorer vs. pressing Enter in Far but there must be some obviously which are important for xash3d. Don't really want to waste time investigating this one any further so just reporting it here for other people to be aware about one of the possible causes of the "can't initialize cl_dlls/client_amd64.dll" error.

**Comment by a1batross** [comment]
@lexa2 probably Far doesn't set the current working directory for Xash.

Never thought somebody still uses Far. It's probably should be fixed in upstream.

**Comment by vonvrona** [comment]
Have the exact same issue, the reinstallation and .cfg file suggestions that were above didn't help. Has anyone found a solution?

**Comment by OBAViJEST** [comment]
<img width="1273" alt="asf" src="https://user-images.githubusercontent.com/12637059/220987087-21e5e88f-d783-47ba-bfad-f26c3658c2df.png">


Same thing after clean install + .cfg removal...... gtx 1080 gpu

**Comment by soup587** [comment]
happens for me too, 1080 as well

guessing it's just not compatible with gtx cards?

**Comment by theokyr** [comment]
Probably. Same crash in same address as OP on GTX 1060.
![image](https://user-images.githubusercontent.com/9939076/221052368-c7e16297-d01e-412b-83fb-8144b866757e.png)

**Comment by Zorklis** [comment]
> Probably. Same crash in same address as OP on GTX 1060. ![image](https://user-images.githubusercontent.com/9939076/221052368-c7e16297-d01e-412b-83fb-8144b866757e.png)

Well I am running GTX 1060 too

**Comment by BelleNottelling** [comment]
The path tracing render that this uses assumes fp16 support on the GPU and won't work on pascal cards (such as the 1060 or 1080).

**Comment by superblobster** [comment]
> The path tracing render that this uses assumes fp16 support on the GPU and won't work on pascal cards (such as the 1060 or 1080).

These cards have ray tracing support and fp16 support according to this:
https://developer.nvidia.com/cuda-gpus#compute
https://docs.nvidia.com/deeplearning/tensorrt/support-matrix/index.html#hardware-precision-matrix
https://forums.developer.nvidia.com/t/fp16-support-on-gtx-1060-and-1080/53256

**Comment by BelleNottelling** [comment]
> > The path tracing render that this uses assumes fp16 support on the GPU and won't work on pascal cards (such as the 1060 or 1080).
> 
> These cards have ray tracing support and fp16 support according to this: https://developer.nvidia.com/cuda-gpus#compute https://docs.nvidia.com/deeplearning/tensorrt/support-matrix/index.html#hardware-precision-matrix https://forums.developer.nvidia.com/t/fp16-support-on-gtx-1060-and-1080/53256

Interesting, I was basing my comment based on this PR on the path tracing render here:
https://github.com/sultim-t/RayTracedGL1/pull/19

**Comment by Lautaro3590** [comment]
![image](https://user-images.githubusercontent.com/36142918/221088574-87129ed8-cecd-4726-93c5-4d2dbac13908.png)
I'm sure I'm having the same crash message as everyone else?

I'm on a GTX 1060 6GB, I have no idea what to do besides the .cfg method which didn't work.

**Comment by 7Works** [comment]
I have GTX 1660 and I was getting same error (I tried to start xash3d.exe from Unreal Commander)
Starting from Explorer itself fixed this and it ran OK.
I should say though that I've got 60 FPS only on Ultra Perfomance setting, maybe on 1060 and GPUs like this it won't have 60 fps even with this setting.

**Comment by soup587** [comment]
if a 1660's working then it's probably a pascal thing

**Comment by Tuxist** [comment]
i have this crash too with a intel arc 770

**Comment by superblobster** [comment]
> if a 1660's working then it's probably a pascal thing

How can it be a Pascal thing when people with RTX cards are getting the same error???
https://github.com/sultim-t/xash-rt/issues/36#issuecomment-1442767837

**Comment by Preath** [comment]
I have the same problem and having a GTX 1080.

**Comment by CorruptHomie** [comment]
I found the solution; you need to update your "Game Ready Driver" to 528.49 if you use a RTX 30xx/40xx card.

**Comment by GHDavor** [comment]
> I found the solution; you need to update your "Game Ready Driver" to 528.49 if you use a RTX 30xx/40xx card.

that's for rtx, not gtx

**Comment by Cracky64** [comment]
> i have this crash too with a intel arc 770

same here.

**Comment by GHDavor** [comment]
i also tried to install xash 3d, the original one, did all of the installation, then installed the rtx mod and still, i got a sys crash

**Comment by allvpgit** [comment]
1080ti the same issue

**Comment by Zorklis** [comment]
Fixed by https://github.com/sultim-t/RayTracedGL1/pull/31
