### ISSUE TITLE
[Suggestion] Sven Coom Implementation

### ISSUE THREAD

**Issue by ClifffordW** [sultim-t/xash-rt#20]
Would it be possible to implement the Raytracing and DLSS into Sven Coop the multiplayer version of Half life ?

**Comment by francosalcedo** [comment]
It would be amazing, I hope so too

**Comment by notfrying1pans** [comment]
Probably not, Sven Co-Op is it's own thing separate from Xash.

**Comment by slambo311** [comment]
Sven Co-Op runs on a modified engine already, it would be hell to implement.
