### ISSUE TITLE
Rotating Emergency Lights

### ISSUE THREAD

**Issue by countbuggula** [sultim-t/xash-rt#22]
The rotating emergency lights on the ceiling in Unforeseen Consequences are not real light sources - they appear to be translucent boxes and as such look really out of place, especially when the rest of the room is lit so realistically.  Any chance these could be replaced with light sources to dynamically cast light around the room?
![image](https://user-images.githubusercontent.com/578358/220984546-1b436b0b-ae2e-4350-b23c-0f44dd8c29a7.png)

**Comment by sultim-t** [comment]
Sadly, there are some limitations to my library... I really wanted to attach moving lights, but it adds overwhelming amount of noise :(
