### ISSUE TITLE
Console doesn't launch

### ISSUE THREAD

**Issue by Mabadman** [sultim-t/xash-rt#24]
Sorry if this is an obvious user error but I couldn't find anything in the settings to enable the console.
In the config I bound console to P but it doesn't seem to work (neither does tilde)

**Comment by KyleGospo** [comment]
`-console` as a launch option.

**Comment by fl1ppyXD** [comment]
> `-console` as a launch option.

Tried this and tried adding a bind through the config like OP but the console still doesnt work.
