### ISSUE TITLE
G SYNC locked to 56 fps and dirty screen texture

### ISSUE THREAD

**Issue by Airqu0tes** [sultim-t/xash-rt#25]
Hey, first off incredible work! This is so far beyond your ports for Quake and Doom. This is almost like a remaster than just adding RT. The amount of relighting and new geometry must have been a huge job. Thanks for putting this out free! I'm so stoked to play through the whole thing.

A bug and a request:
- I have a 144hz G SYNC monitor and the game seems to be locked to 56 fps for me. Not sure if this is a hard limit to avoid breaking physics or something but thought I would point it out.
- Would it be possible to add an option to disable the dirty window effect when looking at bright lights? Just never been a fan of those effects. 

Anyway thanks again for this incredible project!

**Comment by ghost** [comment]
120Hz here and also locked to 56FPS max.

**Comment by KyleGospo** [comment]
Might be Windows-specific, I can confirm VRR works great on Linux with VRR-patched GNOME.

Are either of you using vsync? What's your fps_max cvar set to?

**Comment by a1batross** [comment]
Xash was never tested on monitors with VRR on Windows. 

It has only one cvar for locking framerate to refresh rate, and it's default gl_vsync, and even then swap interval is handled by SDL2, rather than directly by engine.

**Comment by a1batross** [comment]
I think I figured out what's wrong. @sultim-t didn't rebase his changes on latest upstream master, where I had changed the logic of in-between frame sleep, which initially was made for Xash3D FWGS Android port in like 2016, to decrease battery drain problem. 

To completely disable this, open console and type `sleeptime 0`. Newer engine wouldn't require it, as it sleeps only if frametime allows that. This will also increase the performance! And this potentially can solve sloppy movement issues?..

Then again, in newer engine I have removed the logic to enforce frame limit to display frequency from engine side, which never made any sense and came to us from original Xash3D Engine, and this feature wasn't even wired to video code anyway. 

To workaround, you can set `vid_displayfrequency` cvar to some higher up value than your monitor refresh rate, for example just `vid_displayfrequency 200`. Don't set to 0, it will make the engine think that your refresh rate is 60Hz! In newer engine branches, this cvar doesn't exist in the first place and therefore have no effect.

**Comment by Airqu0tes** [comment]
> I think I figured out what's wrong. @sultim-t didn't rebase his changes on latest upstream master, where I had changed the logic of in-between frame sleep, which initially was made for Xash3D FWGS Android port in like 2016, to decrease battery drain problem.
> 
> To completely disable this, open console and type `sleeptime 0`. Newer engine wouldn't require it, as it sleeps only if frametime allows that. This will also increase the performance! And this potentially can solve sloppy movement issues?..
> 
> Then again, in newer engine I have removed the logic to enforce frame limit to display frequency from engine side, which never made any sense and came to us from original Xash3D Engine, and this feature wasn't even wired to video code anyway.
> 
> To workaround, you can set `vid_displayfrequency` cvar to some higher up value than your monitor refresh rate, for example just `vid_displayfrequency 200`. Don't set to 0, it will make the engine think that your refresh rate is 60Hz! In newer engine branches, this cvar doesn't exist in the first place and therefore have no effect.

Amazing this fixed it. Can confirm I went from 56fps to 110fps+ on my 3080. I also figured out how to disable the dirty lens effect. Edit \Half-Life\valve\RT.cfg and look for the line rt_bloom_dirt "2". Change it to 0 and save and it will disable the effect.

**Comment by sultim-t** [comment]
Now, in [1.0.5](https://github.com/sultim-t/xash-rt/releases/tag/1.0.5) the defaults are:

`gl_vsync 0`
`sleeptime 0`
`vid_displayfrequency 200`
`fps_max 300`

To enable vsync, there is a separate `rt_vsync`
