### ISSUE TITLE
RT presets?

### ISSUE THREAD

**Issue by NineKain** [sultim-t/xash-rt#28]
Would you kindly offer any kind of way to change the RT quality? Default looks great, but its tanking my 3060ti even with DLSS at balanced sometimes

**Comment by tokariu** [comment]
it runs super fluent on 3060 with dlss 2.5.1 quality here. 

but maybe have a look at:
```
./valve/gameinfo.txt
max_edicts	900
max_tempents	500
max_beams		128
max_particles	4096
```

**Comment by NineKain** [comment]
changed it to 

max_edicts	400
max_tempents	100
max_beams		64
max_particles	1024

exact same performance

**Comment by a1batross** [comment]
Do not change anything you don't understand. These values are for entities
and various effects, like particles and beams, which aren't RT specific and
present in original engine as well.

Enter makehelp in console, it will write help.txt file, with a brief
description.

**Comment by NineKain** [comment]
I dont really need help, game runs fine, I just want it to run a tiny bit better, I dont mind sacrificing a bit of RT quality for that

**Comment by tokariu** [comment]
the gameinfo.txt was created by the xash3d engine..

however, the RT settings are rather here to be found:

`./valve/rt.cfg`
look at the rt_XXXXX values.

good luck tweaking all these values, though ;)

**Comment by sultim-t** [comment]
> Would you kindly offer any kind of way to change the RT quality? Default looks great, but its tanking my 3060ti even with DLSS at balanced sometimes

@NineKain The main performance impact is the render resolution.

Of course, `rt_reflrefr_depth` can be used to change amount of reflection/refractions per pixel (0 to disable glass/water/mirrors/etc), but it degrades the image quality. Other cvar-s have little to no performance impact.

So the only preferable way is to change the resolution via FSR/DLSS or vintage modes.
