### ISSUE TITLE
gfx.wad couldn't load

### ISSUE THREAD

**Issue by TheMonkeandratgod** [sultim-t/xash-rt#30]
im a rookie, and i just signed into github. 
i got no idea how to fix this:
![gfx](https://user-images.githubusercontent.com/107513207/221051516-1639e8ab-f928-4a07-b8ba-189ebe557a45.png)

**Comment by jprk05** [comment]
I got that error when I was setting it up too don't worry it's very easy to fix
make sure you extracted hl1-rt.zip and hl1-rt-resources.zip correctly

your files should look like this:
![Screenshot 2023-02-23 164059](https://user-images.githubusercontent.com/56183766/221064524-977a1f96-ee38-4aed-80af-9547d3b220fb.png)

not this:
![Screenshot 2023-02-23 165018](https://user-images.githubusercontent.com/56183766/221064960-8078147a-45ad-43a0-bcf2-080eb197dd2c.png)

also if you do it correctly it should ask you to replace things

**Comment by macseke** [comment]
I had this error because steam didn't install the game right for some reason. I made it recheck the game files, copied over the RT files again, and then it worked.

**Comment by dasbootbee** [comment]
This is still an issue.

Here is what my HL directory looks like:

![image](https://user-images.githubusercontent.com/1261402/221373649-a68d9c90-8ead-4327-844f-b0fafc138a23.png)

**Comment by sultim-t** [comment]
It's Half-Life 2 not Half-Life (1998)

**Comment by dasbootbee** [comment]
Maybe that's the confusion.  It has to be the original release not Half Life Source?

**Comment by dasbootbee** [comment]
@sultim-t Could I suggest updating the docs to make it clear this doesn't work with Half Life Source and requires the original Half Life.

**Comment by callanadams42-create** [comment]
Apk
