### ISSUE TITLE
Forward/backward movement randomly stops working

### ISSUE THREAD

**Issue by mikew** [sultim-t/xash-rt#32]
I haven't even made it to the test chamber and it's happened 3 times. Have to quit and relaunch before they work again.

Whenever it does happen, there's audio of the player character walking, and you constantly move forward very slowly. Strafing still works.

**Comment by a1batross** [comment]
What is your system?

Check if nothing changes cl_forwardspeed or cl_backwardspeed cvars? Print them in console, when the bug happens.

**Comment by mikew** [comment]
Sorry, forgot to mention. This is on Windows 11

Next time it happens I'll look check out those cvars. It's happened twice since, but I've made it to We've Got Hostiles without it happening

**Comment by a1batross** [comment]
Also if you have VRR enabled monitor, please read my comment there: https://github.com/sultim-t/xash-rt/issues/25#issuecomment-1442661030

**Comment by a1batross** [comment]
Update, read it anyway.
