### ISSUE TITLE
strange pink lighting in outdoor environments 

### ISSUE THREAD

**Issue by Donowa93** [sultim-t/xash-rt#33]
![itsagirl](https://user-images.githubusercontent.com/73498757/221060525-5ca6559e-f79f-4705-9d4c-05373f3e3d11.png)
![pink2](https://user-images.githubusercontent.com/73498757/221060735-fb953d05-fe79-45c4-b3aa-02c2b5e3b89b.png)
in outdoor environments, the sky usually casts a super bright, washed out pink light onto the environment and objects. it wasn't this bright in either the original game or the teasers, which makes me think that this is a bug.

**Comment by sultim-t** [comment]
I hope it's not an actual bug.

On the first image, the sun light bounces off the pink rocks and mixes with blueish sky light.
On the second image, the sky is pinky-blueish and the sun itself has a morningly orange tint.

**Comment by Donowa93** [comment]
i know this is closed, but here are some screencaps from the teaser which doesn't have these issues
![oldlighting1](https://user-images.githubusercontent.com/73498757/221292371-01a5a15f-ac83-49ea-b50e-daaa25429031.png)
![oldlighting2](https://user-images.githubusercontent.com/73498757/221292379-7dbca997-4b62-4b96-b4b4-c2a2b3bbdc2d.png)
i guess this could be because you might have both the directional light and sky contributing to the light, and/or because the skybox images might not be hdr. either way, it's nowhere near as bright in the original, black mesa, half-life source, or the teaser.
