### ISSUE TITLE
RT is quite slow to respond to movement

### ISSUE THREAD

**Issue by ruvaldak** [sultim-t/xash-rt#41]
This seems to be inherited from the quake rt port. Not sure why exactly it is, but the raytracing is especially slow, often times leaving spotty, noisy trails in motion, or flickering/volumetric lights looking messy/spotty/noisy. Perhaps too few rays? Something to look in to.

**Comment by sultim-t** [comment]
The light sampling and denoiser temporally reproject the information from previous frames to have a moderately stable image in the end. There should be of course a balance between amount of noise and history length; it just involves either a lot of adjustments to the current system, or rewriting with newer algorithms
