### ISSUE TITLE
volumetric doesn't seems to work like trailer shown

### ISSUE THREAD

**Issue by PorkChopUdon** [sultim-t/xash-rt#43]
There are no blooms that can be seen and a lot of dark patches on the emergency light cones and fake skylight cones.
![noVolumetric](https://user-images.githubusercontent.com/126257234/221186308-8e03ab6b-dfe4-4ef6-b0cf-5a237a6c9e89.png)

trailer
![image](https://user-images.githubusercontent.com/126257234/221186444-c4c055e3-a35b-48da-a537-dd57ce343fa6.png)

![blackCone2](https://user-images.githubusercontent.com/126257234/221187393-fd19ace4-4c57-4184-b890-47b0e50adb43.png)
![blackCone](https://user-images.githubusercontent.com/126257234/221186319-7dcb15d9-a425-41d7-875d-2cabc1bd839b.png)

trailer
![image](https://user-images.githubusercontent.com/126257234/221186861-e35c94d7-a85a-45f8-a75e-0d5573313f07.png)

**Comment by sultim-t** [comment]
Seems like there's no scene / texture data. May you check if `hl1-rt-resources.zip` was installed correctly?

**Comment by PorkChopUdon** [comment]
yes you are right, that solved the problem! thanks
