### ISSUE TITLE
Screenshots are just plain black

### ISSUE THREAD

**Issue by CS-PRO1** [sultim-t/xash-rt#46]
I tried taking screenshots using the game's screenshot tool (bound it to F5 from the controls menu) but when I looked for them I found them in the base Half-Life folder and they were just plain black .PNGs
![c1a0_0000](https://user-images.githubusercontent.com/50755959/221233340-7237b6bb-ac54-4a5a-ae91-d1bf48bca2e4.png)

I tried tweaking some graphics settings like turning FSR off but that didn't help.

_Also a side question. How can one access the console? Didn't find the option for it in the controls and hitting ` doesn't work_

**Comment by sultim-t** [comment]
Screenshots are not supported, external tools like Win+PrintScrn or Geforce Experience can be used.
In 1.0.5, `rt_bin/xash3d-console.bat` was added to launch with a console
