### ISSUE TITLE
Gabe Newel room doesn't show up in RTX Renderer

### ISSUE THREAD

**Issue by DerpedCrusader** [sultim-t/xash-rt#48]
I know i know, quite the bug report

to reproduce:

1. go to map c1a1c
2. fly to where it would be (i don't have coords, sorry, but videos are plentyful)
3. it can be easier to find by going to classic renderer and go behind the world, as you see the cube's outline

![image](https://user-images.githubusercontent.com/13917665/221253767-53c4a764-5703-4e89-a77c-43a5fa0e9d5a.png)

this is exactly where it would be

it's visible in the standard renderer, but without the flashlight, you can see it at all

and r_fullbright seems to be forced off, which kinda sucks

not a big deal, i just found it humorous

**Comment by sultim-t** [comment]
`Oкay`
