### ISSUE TITLE
Flipped texture on retinal scanner in map c2a5 surface tension

### ISSUE THREAD

**Issue by EsterLoken** [sultim-t/xash-rt#49]
Don't know if this affects other retinal scanners as well, but for this one load map c2a5, walk up the ramp and there it is.

![image](https://user-images.githubusercontent.com/33354862/221276165-c36303b0-bd94-4a44-a82f-b67b4bc58482.png)

**Comment by sultim-t** [comment]
Fixed in 1.0.5
