### ISSUE TITLE
Still cant get this to work.

### ISSUE THREAD

**Issue by Ava2003** [sultim-t/xash-rt#53]
Can someone please explain to me with a step by step walkthrough on why the launcher cant find my games path? Ive fought with this for almost 2 hours now and nothing will work, getting fed up with this.

**Comment by Ava2003** [comment]
Nice to see help here is totally and utterly useless

**Comment by OBAViJEST** [comment]
Lmao why is this closed

**Comment by sultim-t** [comment]
Duplicate of #51
