### ISSUE TITLE
Greyed NVIDIA DLSS

### ISSUE THREAD

**Issue by tadejdanev** [sultim-t/xash-rt#63]
in game...did all the required steps....have 3060TI.

**Comment by ghost** [comment]
Same here, 2.5.1 dlss inside rt_bin, cannot enable.

**Comment by TuTuc0** [comment]
Had same issue. Make sure _nvngx_dlss.dll_  file is the correct one. It should have around 35MB.

**Comment by ghost** [comment]
> Had same issue. Make sure _nvngx_dlss.dll_ file is the correct one. It should have around 35MB.

This is unhelpful as it's exactly the same version that worked with 1.0.4. I know it is the correct one. It's 25MB downloaded from techpowerup dlss libraries.

EDIT: ok what did fix it was redoing this step
Download [RayTracedGL1-Bundle-DLSS.zip](https://github.com/sultim-t/RayTracedGL1/releases/tag/hl1-dev)

Replace the original rt_bin/RayTracedGL1.dll with a new one bin/RayTracedGL1.dll from RayTracedGL1-Bundle-DLSS.zip

**Comment by tadejdanev** [comment]
nvngx_dlss is 205KB ? oh i clicked on link and it's 35MB now :)

**Comment by tadejdanev** [comment]
works now :)

**Comment by addeps3** [comment]
I can confirm, experienced and resolved the same issue. Probably it has to do with the file explorers way of asking to replace existing file/UI issues. I downloaded the file directly to the target folder, selected to replace existing and the file still had only about 200kb size.
Weird UI/windows behaviour.
