### ISSUE TITLE
Cant run Xash

### ISSUE THREAD

**Issue by Drogo-man** [sultim-t/xash-rt#78]
Whenever i try to run Xash3d.exe i get this:
![Screenshot 2023-02-26 153656](https://user-images.githubusercontent.com/102727246/221417194-a161f21a-f83b-4959-bdf3-06d50bf353fc.png)

**Comment by wenceslaorl** [comment]
What is your video card?

**Comment by wenceslaorl** [comment]
> Whenever i try to run Xash3d.exe i get this: ![Screenshot 2023-02-26 153656](https://user-images.githubusercontent.com/102727246/221417194-a161f21a-f83b-4959-bdf3-06d50bf353fc.png)

What is your video card?

**Comment by Drogo-man** [comment]
> > Whenever i try to run Xash3d.exe i get this: ![Screenshot 2023-02-26 153656](https://user-images.githubusercontent.com/102727246/221417194-a161f21a-f83b-4959-bdf3-06d50bf353fc.png)
> 
> What is your video card?

Nvm, I can't use it since it's a GTX.
