### ISSUE TITLE
I bound something else to 'X' and overwrote the renderer toggle. How can I get it back?

### ISSUE THREAD

**Issue by rgbeez** [sultim-t/xash-rt#8]
I bound 'last weapon' to the 'X' key without thinking that 'X' is for switching RT renderer with Classic. Resetting all controls to default didn't reset the renderer toggle to 'X'. How can it be reset?

**Comment by rgbeez** [comment]
For now, I found the "rt_classic" setting in Valve/rt.cfg and set it to '0' to turn ray tracing back on.

**Comment by sultim-t** [comment]
Add `bind "x" "rt_classic_toggle"` to the `valve/config.cfg` or to a console
