### ISSUE TITLE
Couldnt Load GFX.WAD

### ISSUE THREAD

**Issue by ozturkish** [sultim-t/xash-rt#81]
Hi Guys just installed the mod to try it out, extracted both files into the root Half-life directory and when I go to run xash3d I get an error saying W_LoadWadFile. couldn't load GFX.WAD.

Any assistance on this? I am running Half-life on steam, NOT the source version.

![Error](https://user-images.githubusercontent.com/126422383/221437972-a6dbebf2-f4f4-4e78-8d48-1e7358aa6d49.jpg)

**Comment by ratsonmars** [comment]
I'm having the same issue, also running on the steam release of hl1

**Comment by Belugaking** [comment]
Ran into the same issue as well, tried with windows 11 and on linux with proton which both gave the same error.

**Comment by KyleGospo** [comment]
Looks like you have it installed incorrectly, should be common/Half-Life/rt_bin, similar to this:
![image](https://user-images.githubusercontent.com/10704358/221487938-50e6f6d4-287d-4173-b086-d8f1612c6e1d.png)

**Comment by ozturkish** [comment]
> Looks like you have it installed incorrectly, should be common/Half-Life/rt_bin, similar to this: ![image](https://user-images.githubusercontent.com/10704358/221487938-50e6f6d4-287d-4173-b086-d8f1612c6e1d.png)

Awesome will try tonight and report back

**Comment by Belugaking** [comment]
Yeah I figured it out, you have to move all the folders within hl1-rt and hl1-rt-resources into the half life folder. The directions were a little misleading.

**Comment by sultim-t** [comment]
Must be like this
![image](https://user-images.githubusercontent.com/31703959/221709905-9768c762-2a01-4eb3-9812-1dbf27cb8b0c.png)

**Comment by ozturkish** [comment]
yep issue was it extracted them into their own folders, all good copied the files out, and works perfectly now. Looks amazing

**Comment by skincrawl** [comment]
I have rt and rt_bin in the Half-Life folder but I still get the same error. :/ I'm on Linux and launching through Steam, using Proton.

<img width="1430" height="870" alt="Image" src="https://github.com/user-attachments/assets/e969facc-6e95-4a40-933b-d7acfba69fc6" />

**Comment by skincrawl** [comment]
Nevermind, I got it to work. I reinstalled Half Life from Steam and re-added the mod. And it had to be on Proton Experimental for it to work. 🙂
