### ISSUE TITLE
Can't load xash

### ISSUE THREAD

**Issue by hyperc0smo** [sultim-t/xash-rt#82]
![Screenshot (1)](https://user-images.githubusercontent.com/126433286/221456513-daeb7013-ed3c-4019-89cc-39d7579ffee1.png)

**Comment by hyperc0smo** [comment]
i think im dumb and did something wrong

**Comment by hyperc0smo** [comment]
now im getting GFX.WAD missing or something

**Comment by mastan-rus** [comment]
You've unpacked them incorrectly.
See https://github.com/sultim-t/xash-rt/issues/30#issuecomment-1442637561
