### ISSUE TITLE
Refresh rate appears to be locked at 60Hz

### ISSUE THREAD

**Issue by millerpb** [sultim-t/xash-rt#9]
There may be a setting somewhere that I'm not seeing, but it appears that my refresh rate is locked at 60Hz when I launch through xash3d.

The solution appears to be setting `vid_displayfrequency` in `Half-Life\valve\video.cfg` to whatever refresh rate you're targeting (in my case 120).

**Comment by sultim-t** [comment]
Now, in 1.0.5, it's set to 200 by default
