### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by Tinypig24** [sultim-t/xash-rt#99]
I get a error message on startup that reads "W_LoadWadFile: could't load gfx.wad". Steam version of Half-Life 1 launches fine, no error, but this won't for some reason. gfx.wad is there.
![error](https://user-images.githubusercontent.com/126606334/221936596-699f435a-780b-489e-90ea-9d4bd131694e.PNG)

**Comment by mastan-rus** [comment]
You've probably unpacked archives incorrectly. See https://github.com/sultim-t/xash-rt/issues/30#issuecomment-1442637561
